#!/data/data/com.termux/files/usr/bin/bash

# Get the URL
URL=$1
echo "Opening URL"

# Cheks if it's a Youtube or Spotify URL and downloads it
if [[ $URL == *"open.spotify.com"* ]] ; then
  echo "Spotify link detected"
  spotdl "$URL"
elif  [[ $URL == *"youtu.be"* || $URL == *"youtube.com"* ]]; then
  echo 'Downloading Video'
  yt-dlp -c -i --no-mtime "$URL" -o "$HOME/storage/downloads/Youtube/%(title)s.%(ext)s"

# Runs if it's not a Youtube or Spotify URL
else
  echo "URL type not Youtube or Spotify, attempting to download with yt-dlp"
  yt-dlp -c -i --no-mtime "$URL" -o "$HOME/storage/downloads/%(title)s.%(ext)s"
fi

if [ $? -eq 0 ]; then
    echo "Download successful!"
else
    echo "Download failed. Please check the URL and your connection."
fi

read -n 1 -s -p "Press any key to exit..."
